//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLaboratoryPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Arc_DBEntities : DbContext
    {
        public Arc_DBEntities()
            : base("name=Arc_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<ModelingResult> ModelingResults { get; set; }
        public virtual DbSet<ModelingTask> ModelingTasks { get; set; }
        public virtual DbSet<ModelingTestInput> ModelingTestInputs { get; set; }
        public virtual DbSet<SourceModal> SourceModals { get; set; }
        public virtual DbSet<StudyGroup> StudyGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
