//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLaboratoryPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelingTestInput
    {
        public int id { get; set; }
        public byte[] input_modal { get; set; }
        public byte[] output_modal { get; set; }
        public int task_id { get; set; }
    
        public virtual ModelingTask ModelingTask { get; set; }
    }
}
