//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLaboratoryPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelingTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelingTask()
        {
            this.ModelingResults = new HashSet<ModelingResult>();
            this.ModelingTestInputs = new HashSet<ModelingTestInput>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public string first_part { get; set; }
        public string middle_part { get; set; }
        public string last_part { get; set; }
        public string task_complex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelingResult> ModelingResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelingTestInput> ModelingTestInputs { get; set; }
    }
}
