//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLaboratoryPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelingResult
    {
        public int id { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> result_description { get; set; }
        public int source_modal_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public int modeling_task_id { get; set; }
    
        public virtual ModelingTask ModelingTask { get; set; }
        public virtual SourceModal SourceModal { get; set; }
        public virtual User User { get; set; }
    }
}
